### ISSUE TITLE
Distribution Checklist and Progress

### ISSUE THREAD

**Issue by lockwo** [lockwo/distreqx#4]
- [x] Bernoulli
- [ ] beta
- [ ] categorical
- [ ] categorical uniform
- [ ] clipped
- [ ] deterministic
- [ ] dirichlet
- [ ] epsilon greedy
- [ ] gamma
- [ ] greedy
- [ ] gumbel
- [x] independent
- [ ] joint
- [ ] Laplace
- [ ] log stddev normal
- [ ] logistic
- [ ] mixture of two
- [ ] mixture same family
- [ ] multinomial
- [x] mvn_diag
- [ ] mvn diag plus low rank
- [x] mvn from bijector
- [ ] mvn full covariance
- [ ] mvn tri
- [x] normal
- [ ] one hot categorical
- [ ] quantized
- [ ] softmax
- [ ] straight through
- [x] transformed
- [ ] uniform
- [ ] von mises

**Comment by gvcallen** [comment]
Hey @lockwo, this is just a bump regarding my open PRs. No real rush but I've managed to narrow down the ones that are most important for my downstream libraries (which currently depend on my local fork of distreqx) which I thought I'd list here so you could tackle these first when you have a chance.

The priority distribution-related PRs are:
- TruncatedNormal
- ImproperUniform
- Joint
